site_name: MaterialValues
pages:
- Home: index.md
- Style:
    - Colors: style/colors.md
    - Icons: style/icons.md
    - Typography: style/typography.md
- Layout:
    - Metrics & keylines: layout/keylines.md
    - Responsive UI: layout/responsive_ui.md
    - Elevation: layout/elevation.md
    - Structure: layout/structure.md
- Components:
    - Bottom navigation: component/bottom_navigation.md
    - Bottom sheet: component/bottom_sheet.md
    - Buttons: component/buttons.md
    - Buttons (FAB): component/buttons-fab.md
    - Cards: component/card.md
    - Chips: component/chips.md
    - Dialogs: component/dialogs.md
    - Dividers: component/dividers.md
    - Expansion panels: component/expansion_panels.md
    - Grid lists: component/grid_lists.md
    - Lists: component/lists.md
    - Menus: component/menus.md
    - Steppers: component/steppers.md
    - Subheaders: component/subheaders.md
    - Tooltips: component/tooltips.md
- About:
    - Changelog: about/changelog.md
theme: flatly
extra_css:
    - css/extra.css
repo_url: https://github.com/AoDevBlue/MaterialValues
google_analytics: ['UA-86460261-1', 'aodevblue.github.io']
copyright: MaterialValues 1.1.0

